# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/users/braed/repos/Crawl-The-Dungeon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/braed/repos/Crawl-The-Dungeon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/braed/repos/Crawl-The-Dungeon/CMakeFiles /mnt/c/Users/braed/repos/Crawl-The-Dungeon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/braed/repos/Crawl-The-Dungeon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crawl_the_dungeon

# Build rule for target.
crawl_the_dungeon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crawl_the_dungeon
.PHONY : crawl_the_dungeon

# fast build rule for target.
crawl_the_dungeon/fast:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/build
.PHONY : crawl_the_dungeon/fast

Soldier.o: Soldier.cpp.o

.PHONY : Soldier.o

# target to build an object file
Soldier.cpp.o:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/Soldier.cpp.o
.PHONY : Soldier.cpp.o

Soldier.i: Soldier.cpp.i

.PHONY : Soldier.i

# target to preprocess a source file
Soldier.cpp.i:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/Soldier.cpp.i
.PHONY : Soldier.cpp.i

Soldier.s: Soldier.cpp.s

.PHONY : Soldier.s

# target to generate assembly for a file
Soldier.cpp.s:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/Soldier.cpp.s
.PHONY : Soldier.cpp.s

TilesEnum.o: TilesEnum.cpp.o

.PHONY : TilesEnum.o

# target to build an object file
TilesEnum.cpp.o:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/TilesEnum.cpp.o
.PHONY : TilesEnum.cpp.o

TilesEnum.i: TilesEnum.cpp.i

.PHONY : TilesEnum.i

# target to preprocess a source file
TilesEnum.cpp.i:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/TilesEnum.cpp.i
.PHONY : TilesEnum.cpp.i

TilesEnum.s: TilesEnum.cpp.s

.PHONY : TilesEnum.s

# target to generate assembly for a file
TilesEnum.cpp.s:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/TilesEnum.cpp.s
.PHONY : TilesEnum.cpp.s

final.o: final.cpp.o

.PHONY : final.o

# target to build an object file
final.cpp.o:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/final.cpp.o
.PHONY : final.cpp.o

final.i: final.cpp.i

.PHONY : final.i

# target to preprocess a source file
final.cpp.i:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/final.cpp.i
.PHONY : final.cpp.i

final.s: final.cpp.s

.PHONY : final.s

# target to generate assembly for a file
final.cpp.s:
	$(MAKE) -f CMakeFiles/crawl_the_dungeon.dir/build.make CMakeFiles/crawl_the_dungeon.dir/final.cpp.s
.PHONY : final.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crawl_the_dungeon"
	@echo "... Soldier.o"
	@echo "... Soldier.i"
	@echo "... Soldier.s"
	@echo "... TilesEnum.o"
	@echo "... TilesEnum.i"
	@echo "... TilesEnum.s"
	@echo "... final.o"
	@echo "... final.i"
	@echo "... final.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

