name: Linux Build

on: [push]

jobs:
  build: 

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run_CMake
      run: |
        cmake .
        cmake --build .
    - uses: actions/upload-artifact@v1
      with:
        name: crawl_the_dungeon
        path: /home/runner/work/Crawl-The-Dungeon/Crawl-The-Dungeon
