name: C/C++ CI

on: [push]

jobs:
  build: 

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run CMake
      env:
        CC: ${{ matrix.compiler }}  
        SDL2_DIR: Libs/SDL2-2.0.7
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq cppcheck
        sudo apt-get install -qq libsdl-dev libsdl2-image-dev libsdl2-ttf-dev
        cmake .
