name: Windows Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run_CMake
      env:
        CC: ${{ matrix.compiler }}  
        SDL2_DIR: Libs/SDL2-2.0.7
      run: |
        cmake .
        cmake --build .
    - uses: actions/upload-artifact@v1
      with:
        name: Crawl-The-Dungeon
        path: /home/runner/work/Crawl-The-Dungeon
